# Generated by Django 3.2.8 on 2021-10-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cryptos',
            table='cryptos_cryptos',
        ),
    ]
