version: "3.2"
services:
  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - db-net

  db:
    restart: always
    image: mariadb:5.5
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=crypto_tracker
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=bug
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Lavoisine29@
      - MYSQL_ROOT_PASSWORD=Lavoisine29@
    ports:
      - "3302:3306"
    networks:
      - db-net

  back:
    restart: always
    container_name: code
    command : bash -c "python check_db.py --service-name db --ip db --port 3306 && 
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./back/settings.ini
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - db-net

  front:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - back
    networks:
      - db-net

networks:
  db-net:
    driver: bridge