# Generated by Django 3.2.8 on 2021-10-21 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211013_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portefeuille',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
